PROMPTS:
  translator:
    system_message: |
      You are a proficient translator. Your task is to translate the given text from German to English.
      Example: 
      Input: 'Ich bin ein Berliner.'
      Output: 'I am a Berliner.'
    user_message: |
      Input {input}.
  rephraser:
    system_message: |
      Your task is to rephrase a report of a dream focusing on the description itself rather than the fact that it was a dream.
      Example: 
      Input: 'I dreamt about flying over the city. I felt like I left the ground and soared into the sky. It was exhilarating.' 
      Output: 'I flew over the city. I left the ground and soared into the sky. It was exhilarating.'

      The language could be German or English. Please rephrase the text in the same language.
    user_message: |
      Input {input}.
  interpreter:
    system_message: |
      You are an expert in dream analysis. Your task is to analyze a given dream narrative and extract key details to populate a structured form. The form includes the following categories:

        Description:
            A brief summary of the dream narrative.

        Characters:
            For each character, provide:
                number: An identifier or order number.
                gender: The character's gender (e.g., "male", "female", etc.).
                identity: The character’s role or relationship (e.g., "self", "mother", "stranger").
                age: The character’s age if known.

        Social Interactions:
            Provide scores or descriptive values for:
                aggression: Level/frequency of aggressive interactions.
                friendliness: Level/frequency of friendly interactions.
                sexuality: Presence/intensity of sexual interactions.

        Activities:
            Provide scores or descriptive values for:
                physical: Measure of physical activity.
                movement: Intensity or frequency of movement.
                location_change: Frequency of changes in location.
                verbal: Amount of verbal communication.
                expressive_communication: Level of non-verbal expressive communication.
                visual: Vividness or intensity of visual imagery.
                auditory: Clarity or intensity of sounds.
                thinking: Level of internal dialogue or cognitive activity.

        Emotions:
            Provide scores or descriptive values for:
                anger
                apprehension
                sadness
                confusion
                happiness

        Settings:
            Provide details on the dream’s setting, including:
                location: A description of the setting.
                indoor: Whether the setting is indoors (true/false).
                outdoor: Whether the setting is outdoors (true/false).
                ambiguous: Whether the setting is ambiguous (true/false).
                no_setting: Whether no clear setting is present (true/false).
                familiarity: A descriptor for the familiarity (e.g., "familiar", "distorted", "geographical", "unfamiliar", "questionable").
                Additionally, include boolean flags for:
                    familiar
                    distorted
                    geographical
                    unfamiliar
                    questionable

      Using the dream narrative provided, extract and infer the relevant details for each category. If certain details are not explicitly mentioned, use null or default values as appropriate. Output your result as a JSON structure that matches the structured form.
    user_message: |
      Dream narrative: {input}.

COMPLETION:
  gpt-40-mini:
    type: azure
    model: gpt-4o-mini
    temperature : 0
    max_tokens : 16384
    top_p : 0
    frequency_penalty : 0
    presence_penalty : 0
    best_of : 1
    stop : None
    endpoint: https://azureaihub5783833627.openai.azure.com
    version: "2024-08-01-preview"
    max-requests: 300
    time-span: 60
  gpt-40:
    type: azure
    model: gpt-4o
    temperature: 0 
    max_tokens : 16384
    top_p : 0
    frequency_penalty : 0
    presence_penalty : 0
    best_of : 1
    stop : None
    endpoint: https://mida-azure-openai.openai.azure.com
    version: "2024-08-01-preview"
    max-requests: 200
    time-span: 60

EMBEDDING:
  large:
    type: azure
    model : text-embedding-3-large
    engine: ''
    vectordim: 3072
    endpoint: https://azureaihub5783833627.openai.azure.com
    version: "2023-05-15"
    max-requests: 30
    time-span: 60
  small:
    type: azure
    model : text-embedding-3-small
    engine: ''
    vectordim: 1536
    endpoint: https://azureaihub5783833627.openai.azure.com
    version: "2023-05-15"
    max-requests: 30
    time-span: 60


DEFAULT:
  completion: gpt-40-mini # One of GPT40 or GPT40-MINI
  embeddings: large # one of Ada, Small, Large

GOOGLE:
  ## Google Ads API
  ads-service: "GoogleAdsService"
  keywords-service:
    name: "KeywordPlanIdeaService"
    type: "GenerateKeywordHistoricalMetricsRequest"
  targets: 
    germany: "2276" 
    german: "1000"
  max-requests: 1
  time-span: 2
  ## Google Search Console API
  max-rows: 75000
  row-limit: 25000
  start-date-gap: 2
  past-months-window: 3